
TRAINING_DATA = "TRAIN_DATA/1MillionPasswords.txt"
TESTING_DATA =  "TEST_DATA/UPDATE_PWD_TEST.txt"
GUESS_NUMBER_DATA_SAVE = "GUESS_NUMBER"
MIN_NGRAM = 5
MAX_NGRAM = 7
BACKOFF_THRES = 10
SAMPLE_SIZE = 200